### ISSUE TITLE
SlotTracker and Helper Functions

### ISSUE THREAD

**Issue by carismoses** [roselone/pmGen#2]
Hi @roselone. I am working at upgrading pmGen to work with llvm 5.0 and I am stuck on something. I know you haven't worked on this in a while, but I was hoping you would me able to answer a question of mine.

I noticed that the SlotTracker and the Helper classes are already classes in the llvm libraries (Helper is called AsmWriter in llvm). I was wondering why you made your own versions of them? Are you using the framework of AsmWriter and making it a PROMELA code writer? I am getting errors since a lot of the functions already exist:

`g++ -fno-rtti -O0 -g -o bin/pmGen build/main.o build/IO.o build/TypeGen.o build/TypeFinder.o build/SlotTracker.o build/Helper.o '/home/build/llvm/bin/llvm-config --ldflags --libs --system-libs'`

`/home/build/llvm/lib/libLLVMCore.a(AsmWriter.cpp.o): In function 'llvm::SlotTracker::getLocalSlot(llvm::Value const*)':
/home/llvm/lib/IR/AsmWriter.cpp:996: multiple definition of 'llvm::SlotTracker::getLocalSlot(llvm::Value const*)'
build/SlotTracker.o:/home/pmGen/lib/Helper/SlotTracker.cpp:162: first defined here`

`/home/build/llvm/lib/libLLVMCore.a(AsmWriter.cpp.o): In function 'llvm::SlotTracker::getGlobalSlot(llvm::GlobalValue const*)':
/home/llvm/lib/IR/AsmWriter.cpp:976: multiple definition of 'llvm::SlotTracker::getGlobalSlot(llvm::GlobalValue const*)'
build/SlotTracker.o:/home/pmGen/lib/Helper/SlotTracker.cpp:142: first defined here`

`/home/build/llvm/lib/libLLVMCore.a(AsmWriter.cpp.o): In function 'llvm::SlotTracker::getMetadataSlot(llvm::MDNode const*)':
/home/llvm/lib/IR/AsmWriter.cpp:986: multiple definition of 'llvm::SlotTracker::getMetadataSlot(llvm::MDNode const*)'
build/SlotTracker.o:/home/pmGen/lib/Helper/SlotTracker.cpp:152: first defined here
collect2: error: ld returned 1 exit status`

`make: *** [bin/pmGen] Error 1`

Also I moved the SlotTracker code into its own header and .cpp files. I could probably figure out which flag is loading the AsmWriter lib, but I still have my question of why you made your own version of AsmWriter and SlotTracker. Thank you!

**Comment by carismoses** [comment]
I fixed the problem by `inline`ing the SlotTracker functions! Still have my other question though... Thanks!

**Comment by roselone** [comment]
@carismoses Great! As you know, I do not work on this project for a long time. But, I will try my best to explain the project for you. If you have any questions, feel free to ask me anytime!

pmGen is an llvm backend (converts the LLVM IR to promela).  Document about how to write an llvm backend is [here](http://llvm.org/docs/WritingAnLLVMBackend.html). 

However, after reading llvm-2.9 source code, I did not follow the steps of the document. 
I think only three parts are needed for the backend:

1. A function pass. (FunctionGen.cpp)
2. A type manager. (TypeGen.cpp)
3. An Instruction Writer (Helper.cpp)

AsmWriter is an instruction writer for llvm IR. So I copied the code to my own project and split it into Helper and SlotTracker. 

This is a quicker but dirty approach I think. 
Maybe follow the document is better.

**Comment by carismoses** [comment]
Thanks @roselone. I am still a little bit confused but I'm sure it will make more sense as I get more familiar with the code. I am still having the issue with SlotTracker however. Turns out `inline`ing didn't fix it. The FunctionGen code keeps calling the llvm library functions for the SlotTracker class (in AsmWriter.cpp) instead of the SlotTracker functions from pmGen. Do you remember having this issue?

**Comment by roselone** [comment]
How do you make the project?
Why do you put SlotTracker.cpp under /home/pmGen/lib/Helper/ ?
What is the output of '/home/build/llvm/bin/llvm-config --ldflags --libs --system-libs'?
What is your gcc version when you compile llvm-2.9? I seems that my gcc(7.1) is  incompatibility with llvm-2.9 now.
What is llvm-5.0? Do you mean 4.0?

**Comment by carismoses** [comment]
I pushed my code to my forked copy of [pmGen](https://github.com/carismoses/pmGen). You can take a look at my Makefile. LLVM no longer uses autoconf so I changed everything to just use one central Makefile. I am pretty new to a lot of this so let me know if you have any questions.

I just moved the SlotTracker function definitions into their own file to clean things up a bit for my understanding. No other reason. I tried moving them back to Helper.cpp and compiling but still had the `multiple definitions` error.

**Comment by carismoses** [comment]
I made a new branch where I changed the class name to NewSlotTracker. Not the most elegant fix, but at least now it compiles so I can work on other things :)

**Comment by carismoses** [comment]
Don't worry about the SlotTracker issue. My temporary fix is fine for now. I will try to figure it out some other time. Right now I am just trying to get to a point where I can recreate your .pml files. I am pretty close but have a few issues. I have added my .pml files (as well as the .ll files I used to generate them) to the sample directory in my fork of pmGen in the NewSlotTracker branch with the prefix caris_ ([here](https://github.com/carismoses/pmGen/tree/NewSlotTracker/sample)).

1. Your .pml files us both 'v' and 'tmp' prefixes for unnamed variable names. It's not a huge deal, but I was wondering if there is a difference between the two? And if so, where would it be distinguished in the code? The 'v' prefix is added in FunctionGen::localValueDeclare() but I don't see where a 'tmp' prefix would be added.

2. Before the global variables are printed I get a few weird statements. They are generated by the 
`TypeGener.gen(numberedTypes,m->getValueSymbolTable(),outs())` call in main.cpp. I believe they are the types of the named types. Do you comment this line out typically so it doesn't appear in the .pml output? Below is an example of what it looks like. I commented this function call out in my main.cpp so you won't see it in my caris_*.pml files.

    `TYPEDEF n_0 {  u0;}`
`int (int)`
`int (int, ...)`
`int ()`
`int[16]`
`int (, n_0, year, int)`


3. I noticed in wakeup.pml you have an atomic { } function definition. I am not getting that in my generated .pml file and don't see where in the code it would attempt to insert an "atomic"statement.

4. At the bottom of all of your zune.pml and peterson.pml files you have an ltl formula definition which looks looks like this:
`ltl p1 { [] ((_year@Label0) -> (<>(_year@Label10))) }` 
Where in the code is that generated?

5. You use a flag variable in some of your pml functions. I don't see where they are initialized in the output .pml files. As for the fact that mine say _flag[_flag] instead of _flag[0] I can try to figure out why that's happening. I just can't find anywhere in the code that generates a 'flag' variable.

There are some other small differences but I think I should be able to figure those out. I know you haven't looked at this in a while so if your answer is I have no idea that's totally fine. Just figured I should ask. Thanks!

**Comment by carismoses** [comment]
Fixed issue #5!
